# Generated by Django 3.1.1 on 2020-10-08 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_tip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_telegram_connected', models.BooleanField(default=False)),
                ('telegram_hash', models.CharField(default=None, max_length=40, null=True, unique=True)),
                ('teleram_id', models.CharField(default=None, max_length=64, null=True)),
                ('telegram_username', models.CharField(default=None, max_length=32, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
