# Generated by Django 3.1.1 on 2020-10-09 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='teleram_id',
            new_name='telegram_id',
        ),
    ]
